### ISSUE TITLE
expanded examples cause an error

### ISSUE THREAD

**Issue by Foxcapades** [VEuPathDB/script-raml-merge#7]
Given a RAML example in the style:
```yaml
example:
  displayName: Imported and Installed
  description: |
    A dataset that has been imported and has reached the installation
    phase of the process.
  value:
    import: imported
    install:
    - projectID: PlasmoDB
      status: invalid
```

The raml merge tool throws an error saying: "cannot convert type yaml.Node to a scalar node"

This is true of the `examples` block as well.
